services:
  postgres:
    image: postgres:16
    container_name: scraper-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: scraper
    ports:
      - 5432:5432
    volumes:
      - local-volume:/var/lib/postgresql/data
    networks:
      - local-network

  reactjs:
    container_name: scraper-fe
    build:
      context: ./client
      dockerfile: Dockerfile
    image: scraper-fe:latest
    ports:
      - 80:80
    networks:
      - local-network
    depends_on:
      - postgres
      - nodejs

  nodejs:
    container_name: scraper-be
    build:
      context: ./server
      dockerfile: Dockerfile
    image: scraper-be:latest
    ports:
      - 3001:3001
    networks:
      - local-network
    depends_on:
      - postgres

volumes:
  local-volume:

networks:
  local-network:
    name: local-network
    driver: bridge
