services:
  postgres:
    container_name: ra-postgres
    image: postgres:16
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: local_ra
    ports:
      - 5432:5432
    volumes:
      - ./local_ra.sql:/local_ra.sql
      - local-ra:/var/lib/postgresql/data
    networks:
      - local-ra

  redis:
    container_name: ra-redis
    image: redis
    ports:
      - 6379:6379
    networks:
      - local-ra

  nestjs:
    container_name: ra-be
    platform: linux/amd64
    build:
      context: ./rival-ambassador-be
    image: phuvietdang/ra-be:latest
    ports:
      - 3001:3001
    networks:
      - local-ra
    depends_on:
      - redis
      - postgres

  nextjs:
    container_name: ra-fe
    build:
      context: ./rival-ambassador-fe
    image: phuvietdang/ra-fe:latest
    ports:
      - 3000:3000
    networks:
      - local-ra
    depends_on:
      - nestjs

volumes:
  local-ra:

networks:
  local-ra:
    name: local-ra
    driver: bridge
